### PR TITLE
Convert to UTF8

### PR DESCRIPTION
**Pull request by bbannon**
Convert files to UTF-8 format.
However, keep files like japanese-sjis.txt because the translations are different from Japanese utf-8.

### CODE REVIEW

**Comment by craigk5n** [comment]
Hmmm... I cannot seem to merge this request.  There are conflicts with the master branch.  When I use the command-line merge instructions,  I get "Sorry, this diff is unavailable."

**Comment by craigk5n** [comment]
Still interested in this pull request if you can update it with a commit that fixes the merge conflicts....

**Comment by bbannon** [comment]
All I have to work with is an old tablet. Can barely do this note or email. When I get new computer, I'll have to redo pull request. You may need to just close this for now.

**Comment by craigk5n** [comment]
Closing since it has too many conflicts to merge in its current state.

**Pull request closed without merging**
