### PR TITLE
let's try again

### PR DESCRIPTION
**Pull request by bbannon**
Since I'm supposed to include composer.lock, too.
I also included the updated vendors, because why not?

### CODE REVIEW

**Comment by craigk5n** [comment]
Ummmm... definitely do not want to add the `vendor` directory since it bloats the git repo.  My `vendor` directory is currently 54 Mb.  That would make the default [webcalendar zip download](https://github.com/craigk5n/webcalendar/archive/refs/heads/master.zip) of the repo **HUGE**. It's currently about 7 Mb. See comments in `Makefile` about CKEditor and how updating that one is handled.

**Comment by bbannon** [comment]
OK. I can see that.
But, I had to delete the line for 'vendor' dir in my .gitignore to even see
it for either upload or download.
So, while I think it needs to be somewhere in the repo where devs can get
to it,
I don't think it has to be in the main distribution files. I may be wrong.

If you want to just change the composer files,
I deleted the lines in the require section,
ran require for each one in alphabetic order
(because I wanted to see if they were inserted in the order i typed them;
they are)
including adding components/font-awesome and components/normalize.css.

**Comment by craigk5n** [comment]
Have you tested WebCalendar with bootstrap 5?  Last time I looked, it wasn't a drop-in replacement for bootstrap 4.

**Comment by bbannon** [comment]
I have trouble with bootstrap any version.
I don't know what I'm doing wrong.

One reason I'm trying font-awesome.

**Comment by craigk5n** [comment]
What do you mean by "trying font-awesome"?  I would think there would be a lot of CSS and other changes with a pull request to switch over the font-awesome, so I'm a bit confused about this one.

**Comment by bbannon** [comment]
I'm still experimenting.
At the moment, I'm just hard coding the links into the vendor dir

**Pull request closed without merging**
