### PR TITLE
New default configs and style updates.

### PR DESCRIPTION
**Pull request by bbannon**
Some default configs were left out but, they're in styles.php. Also, a couple of new ones.

### CODE REVIEW

**Comment by craigk5n** [comment]
- I get a PHP compile error on install/default_config.php.
- This change also reverts the layout on my system to inconsistent fonts (looks like $FONT_FAMILY is not being used, so menu fonts are different than the rest of the page)
- And the mini calendars stacked on top of each other:

image

**Comment by bbannon** [comment]
That doesn't make sense. I got no errors when I ran it. I just looked over the diff again. I can't see anything I did that would cause compile errors. I just added some defaults and deleted some comments. I don't see any missing commas or parentheses or anything. I moved border-radius below -moz-border-radius where it belongs. I don't see $FONT_FAMILY anywhere, just --def-font-family. But it's only used as a fall-back if --fonts is undefined. I don't see anything that would cause the mini-cals to stack like that. Or, for that matter, to NOT stack like that, either.

**Comment by bbannon** [comment]
Any thoughts about minimum versions? Or, can that line comment be removed, too?

**Comment by bbannon** [comment]
Hey, Craig.
Are you using node.js and gulp and such?
I'm just starting getting with these things.
If you are, would you mind sending me your package-json and gulpfile.js files?

**Pull request closed without merging**
