### PR TITLE
better versions of font-awesome and normalize.css

### PR DESCRIPTION
**Pull request by bbannon**
I updated the rest.
Not sure if that's a good thing.

### CODE REVIEW

**Comment by craigk5n** [comment]
Looks like it's failing the tests because composer.lock was not updated.  Would't it be better to just let composer infer the latest compatible versions of these dependencies (i.e. "dependency management")?  I don't understand the goal here...

**Comment by bbannon** [comment]
I ran composer require for component/font-awesome and
component/normalize.css
Those are better versions than the ones I did the first time.
When I did that, my other composer packages got auto updated.

I haven't had any problems, but I'm not completely sure yet
that newer versions of the other composer packages don't break webcalendar.
So, I left composer.lock out of the commit.

The goal is to start using some free icons from font awesome that are
smaller file size than what we have and look better.
There are also a couple thousand free options and I think we could let our
users decide which they like.
Also, to use normalize.css to make all browsers, especially edge and
symphony, start off with the same css 'defaults'.
Without updating styles.css very often.

**Comment by craigk5n** [comment]
You need to include composer.json and compose.lock in the same PR for it to pass the tests.

**Comment by bbannon** [comment]
Ah. That explains a few things.
Is that only if package versions change?
Maybe you could just require those 2 packages on your end and see what
happens to the other packages.

**Pull request closed without merging**
