### PR TITLE
Attemp at using css variables

### PR DESCRIPTION
**Pull request by bbannon**
Move now static CSS from styles.php to styles.css to facilitate caching styles.css without the need to got through css_cacher.php.

Add file includes/css/punctuation.css.
Use classes in html to take puncuation out of the code and let the translators use the punctuation they need in their languages.

Question: The changes I made in functions.php are showing in this request as well. I thought I put that in a different branch. Are they always combined? Or do I need to change something next time?

### CODE REVIEW

**Comment by craigk5n** [comment]
Hi, Bruce.

What changes are shown depends on how you created the branch.  What branch were you in when you created this branch?  Also, one I merge the prior changes in, you can then merge or rebase those changes into your branch and prior changes will no longer be included.

**Comment by craigk5n** [comment]
Hey, Bruce.  Not sure if this was intended.  But the latest CSS changes the month layout appearance.  The color changes from System Settings (no user prefs are set) don't seem to be taking affect.  See screenshot below.  The month cell backgrounds should be grey.

image

**Comment by craigk5n** [comment]
Also, I noticed the following PHP warnings in the error.log file:

[Sun Jul 30 14:31:52.444210 2017] [:error] [pid 1192] [client 172.17.0.1:52034] PHP Warning:  ob_start(): function 'ob_gzhandler' not found or invalid function name in /web/html/webcalendar/js_cacher.php on line 34, referer: http://192.168.0.26:8081/webcalendar/month.php?date=20170701
[Sun Jul 30 14:31:52.444411 2017] [:error] [pid 1192] [client 172.17.0.1:52034] PHP Notice:  ob_start(): failed to create buffer in /web/html/webcalendar/js_cacher.php on line 34, referer: http://192.168.0.26:8081/webcalendar/month.php?date=20170701
[Sun Jul 30 14:31:52.582940 2017] [:error] [pid 1190] [client 172.17.0.1:52028] PHP Notice:  Undefined index: BGIMAGE in /web/html/webcalendar/includes/css/styles.php on line 146, referer: http://192.168.0.26:8081/webcalendar/month.php?date=20170701
[Sun Jul 30 14:31:52.583035 2017] [:error] [pid 1190] [client 172.17.0.1:52028] PHP Notice:  Undefined index: MINICALFONT in /web/html/webcalendar/includes/css/styles.php on line 153, referer: http://192.168.0.26:8081/webcalendar/month.php?date=20170701
[Sun Jul 30 14:31:52.583050 2017] [:error] [pid 1190] [client 172.17.0.1:52028] PHP Notice:  Undefined index: MINICALWIDTH in /web/html/webcalendar/includes/css/styles.php on line 154, referer: http://192.168.0.26:8081/webcalendar/month.php?date=20170701
[Sun Jul 30 14:31:52.583060 2017] [:error] [pid 1190] [client 172.17.0.1:52028] PHP Notice:  Undefined index: NEXTMONTHBG in /web/html/webcalendar/includes/css/styles.php on line 156, referer: http://192.168.0.26:8081/webcalendar/month.php?date=20170701
[Sun Jul 30 14:31:52.583069 2017] [:error] [pid 1190] [client 172.17.0.1:52028] PHP Notice:  Undefined index: PREVMONTHBG in /web/html/webcalendar/includes/css/styles.php on line 159, referer: http://192.168.0.26:8081/webcalendar/month.php?date=20170701

**Comment by craigk5n** [comment]
Found a PHP compile error in styles.php that I just committed.

**Comment by bbannon** [comment]
I think I'm getting the hang of it.
Since you've already merged a couple of them in.
They seem to work so, that's a good sign.
Thanks,
Bruce

**Comment by bbannon** [comment]
I used the github master webcalendar for the mods I made. I didn't change the values.
styles.php still needs to go through css_cacher.php to load the values.
I didn't look to see if is or not.
If the $GLOBAL[] wasn't set from the database yet, that would cause the undefined index errors.

The ob_start('ob_gzhandler') thing look like a PHP 5 or 7 issue. I didn't change that from what's in the master. Yet. I'm looking to consolidate all the ob_start/ob_end_flush calls to someplace like print_header/print_trailer.

**Comment by bbannon** [comment]
What was the error in styles.php?
I just looked over the changes I made again and I don't see it.

**Comment by craigk5n** [comment]
See commit here:
https://github.com/craigk5n/webcalendar/commit/fd79256a9ca423ed4b9e51f0dae49da5cda8fe49

**Pull request merged**
