### PR TITLE
example of chaining elvis

### PR DESCRIPTION
**Pull request by bbannon**
This is supposed to select the first that isset(), ! empty() and ! is_null()

see https://stackoverflow.com/questions/34571330/php-short-ternary-elvis-operator-vs-null-coalescing-operator

### CODE REVIEW

**Comment by craigk5n** [comment]
Why are we adding a "en-US.txt" translation file when we already have a "English-US.txt" file?

**Comment by bbannon** [comment]
I'm looking to make all translations/*.txt files into the 'navigator.language' names like captcha, ckeditor and phpmailer use. It would make it easier to copy just the 1 or 2 language files that the user needs. Eventually.

**Comment by craigk5n** [comment]
It's interesting, but I think I'll keep including all or most of the translations in the normal release. This is because the language is supposed to be picked up through the browser, which means that your website supports foreign languages (except for event information). However, we could consider creating a release builder that would allow users to select the languages they want to include. I'm just not sure where it would be hosted.

**Comment by bbannon** [comment]
Could we figure out a checkbox sort of thing in the installer? Let them choose which languages to download. Javascript 'navigator.languages', notice the plural, is an array of all languages the user has set up.

**Comment by bbannon** [comment]
Craig, I think if you delete Elven.txt from your side of this, we could both merge it in.

**Comment by craigk5n** [comment]
I'm not sold on renaming the translation files just yet.  In any case, that change should be a separate PR.

**Comment by bbannon** [comment]
This won't let me 'resolve conflicts'. Can you merge it, if you like the 'chasing Elvis' part? Then delete the *.txt files. Or just close it.

**Pull request closed without merging**
