### PR TITLE
If we use === we don't need to also check for empty()

### PR DESCRIPTION
**Pull request by bbannon**
Cut test time in half.

### CODE REVIEW

**Comment by craigk5n** [comment]
How are undefined variables handled with '==='?  I typically use empty because it is safe to use even with variables that are not defined (and avoids a PHP warning).

**Comment by bbannon** [comment]
empty, NULL and undefined just don't match a non-empty string.
=== compares type as well as content.
Also, I think it's a bit more secure to actually === 'Y' rather than != 'N'
!= 'N' could be anything, including malicious code.

**Comment by craigk5n** [comment]
You still need to check for empty.  I tried the following PHP file:
```<h2>Var Test</h2>
<?php
if ( $UNDEFINED_VARIABLE === 'N' ) {
  echo "This is a test";
} 
?>```
... and I get the following in the error.log:

PHP Notice:  Undefined variable: UNDEFINED_VARIABLE in /web/html/webcalendar/test.php on line 3

And I don't believe our code should be generating any warnings.

**Comment by bbannon** [comment]
hmmm... It worked, so I didn't check the error log. I've been re-reading the php manual; I can't find anywhere it says anything about errors if the variable is empty/null/undefined.
It just says $a === 'Y' is false if $a is not identical to 'Y' in both type and content.

We could just suppress warnings with an @.

**Pull request closed without merging**
